// Copyright Epic Games, Inc. All Rights Reserved.

// =====================================================================================================================
// NetObjectGroups.cpp —— FNetObjectGroups 实现：Group 增删 + 成员维护 + Filter trait 切换 + 全局 GroupFilteredOut 位图。
// 关键不变量：
//   - GroupFilteredOutObjects 中位 i 为 1 ⇔ 对象 i 至少属于一个具有 IsExclusionFiltering 或 IsInclusionFiltering 的 Group；
//   - 对象 ↔ Group 的双向索引（FNetObjectGroup.Members 与 GroupMemberships[obj].GroupIndexes）始终一致；
//   - Handle 含 Epoch + UniqueId，避免 Index 复用引发的 stale handle 误命中。
// =====================================================================================================================

#include "NetObjectGroups.h"
#include "Math/UnrealMathUtility.h"
#include "HAL/IConsoleManager.h"
#include "Iris/Core/IrisLog.h"
#include "Iris/ReplicationSystem/Filtering/NetObjectFilter.h"
#include "Iris/ReplicationSystem/NetRefHandleManager.h"
#include "Containers/ArrayView.h"

DEFINE_LOG_CATEGORY_STATIC(LogIrisGroup, Log, All)

namespace UE::Net::Private
{

	namespace NetObjectGroupsInternal
	{
		/** 全局递增 Epoch 计数器：每次构造 FNetObjectGroups 实例 +1。截断到 EpochMask 范围以适配 handle 的 Epoch 段。 */
		static FNetObjectGroupHandle::FGroupIndexType NextEpoch = 1U;
	}

// 调试 cvar：当某对象成员组数突破阈值时打 ensure，便于排查"无意中加入了过多组"的逻辑错误。
static int32 CVarEnsureIfNumGroupMembershipsExceedsNum = 128;
static FAutoConsoleVariableRef CVarEnsureIfNumGroupMembershipsExceeds(TEXT("net.Iris.EnsureIfNumGroupMembershipsExceeds"), CVarEnsureIfNumGroupMembershipsExceedsNum, TEXT("If set to a positive number we will warn and ensure if an object is added to a high number of groups."), ECVF_Default );

// 构造：递增 Epoch（位掩码截断）；若回绕到 0，发出警告（仅意味长期运行/PIE 多次创建后概率事件）。
FNetObjectGroups::FNetObjectGroups()
: CurrentEpoch((++NetObjectGroupsInternal::NextEpoch) & FNetObjectGroupHandle::EpochMask)
{
	if (CurrentEpoch == 0U)
	{
		UE_LOG(LogIris, Warning, TEXT("FNetObjectGroups::Epoch wraparound detected."));
	}
}

FNetObjectGroups::~FNetObjectGroups()
{
}

// ---------- 静态辅助：Membership 操作 ----------
bool FNetObjectGroups::IsMemberOf(const FNetObjectGroupMembership& Target, FNetObjectGroupHandle Group)
{
	return Target.ContainsMembership(Group);
}

bool FNetObjectGroups::AddGroupMembership(FNetObjectGroupMembership& Target, FNetObjectGroupHandle Group)
{
	if (!Target.ContainsMembership(Group))
	{
		Target.AddMembership(Group);

		return true;
	}

	return false;
}

void FNetObjectGroups::ResetGroupMembership(FNetObjectGroupMembership& Target)
{
	Target.ResetMemberships();
}

// 初始化：clamp MaxGroupCount，把"索引 0"占位为无效组（避免合法 handle 的 Index 为 0），分配 GroupMemberships 与 GroupFilteredOutObjects。
void FNetObjectGroups::Init(const FNetObjectGroupInitParams& Params)
{
	NetRefHandleManager = Params.NetRefHandleManager;

	ensureMsgf(Params.MaxGroupCount <= FNetObjectGroupHandle::MaxGroupIndexCount, TEXT("MaxGroupCount cannot exceed %u"), FNetObjectGroupHandle::MaxGroupIndexCount);
	MaxGroupCount = FMath::Clamp<uint32>(Params.MaxGroupCount, 0U, FNetObjectGroupHandle::MaxGroupIndexCount);

	// Reserve first as invalid group
	// 占位"索引 0"为不可用组：保证 FNetObjectGroupHandle::IsValid() 用 Index!=0 判定能可靠工作。
	Groups.Add(FNetObjectGroup());

	GroupMemberships.SetNum(Params.MaxInternalNetRefIndex);
	GroupFilteredOutObjects.Init(Params.MaxInternalNetRefIndex);
}

// 索引上限扩容：仅扩两个跟"对象数"相关的容器；GroupCount 上限独立。
void FNetObjectGroups::OnMaxInternalNetRefIndexIncreased(FInternalNetRefIndex NewMaxInternalIndex)
{
	GroupMemberships.SetNum(NewMaxInternalIndex);
	GroupFilteredOutObjects.SetNumBits(NewMaxInternalIndex);
}

// 创建组：检查容量上限 + 自动起名 + 唯一性校验 + 分配 GroupId & Index → 返回带 Epoch/UniqueId 的 handle。
FNetObjectGroupHandle FNetObjectGroups::CreateGroup(FName InGroupName)
{
	const bool bCanCreateGroup = (uint32)Groups.Num() < MaxGroupCount;

	if (!bCanCreateGroup)
	{
		UE_LOG(LogIrisGroup, Warning, TEXT("Maximum allowed groups allocated: %u. Group: %s cannot be created"), MaxGroupCount, *InGroupName.ToString());
		ensureMsgf(false, TEXT("FNetObjectGroups::CreateGroup: Maximum allowed groups allocated."));
		return FNetObjectGroupHandle();
	}

	// Auto-generate a name if none was passed	
	// 未指定名字：用 ("NetObjectGroup", N) 自动生成；N 自增防重复。
	if (InGroupName == NAME_None)
	{
		InGroupName = FName(TEXT("NetObjectGroup"), AutogeneratedGroupNameId++);
	}

	// Validate that the given name is unique
	{
		const FNetObjectGroupHandle ExistingGroup = FindGroupHandle(InGroupName);
		if (ExistingGroup.IsValid())
		{
			UE_LOG(LogIrisGroup, Warning, TEXT("Tried to create a group named: %s. But this name was already registered to groupHandle: %u"), *InGroupName.ToString(), ExistingGroup.GetGroupIndex());
			ensureMsgf(false, TEXT("FNetObjectGroups::CreateGroup: Group name %s is already registered"), *InGroupName.ToString());
			return FNetObjectGroupHandle();
		}
		
	}

	const uint32 NewGroupId = NextGroupUniqueId++;
	
	// SparseArray::Emplace 复用空洞，索引稳定。
	const uint32 Index = (uint32)Groups.Emplace(FNetObjectGroup{.GroupName = InGroupName, .GroupId = NewGroupId});

	UE_LOG(LogIrisGroup, Verbose, TEXT("Created GroupHandle named: %s Index: %u Id: %u"), *InGroupName.ToString(), Index, NewGroupId);

	FNetObjectGroupHandle GroupHandle;
	GroupHandle.Index = static_cast<FNetObjectGroupHandle::FGroupIndexType>(Index);
	GroupHandle.Epoch = CurrentEpoch;
	GroupHandle.UniqueId = NewGroupId;

	ensureMsgf(NextGroupUniqueId != 0, TEXT("We created more than MAX_uint32 unique NetGroups. An Id overflow occured and it may cause conflicts with existing handles."));

	return GroupHandle;
}

// 销毁：先清空成员（连带维护 GroupFilteredOutObjects 与对象 Membership），再从 SparseArray 移除。
void FNetObjectGroups::DestroyGroup(FNetObjectGroupHandle GroupHandle)
{
	if (IsValidGroup(GroupHandle))
	{
		FNetObjectGroup& Group = Groups[GroupHandle.GetGroupIndex()];

		UE_LOG(LogIrisGroup, Verbose, TEXT("Destroyed GroupHandle named: %s Index: %u Id: %u"), *Group.GroupName.ToString(), GroupHandle.Index, Group.GroupId);

		ClearGroup(GroupHandle);		
		Groups.RemoveAt(GroupHandle.GetGroupIndex());
	}
}

// 清空成员：对每个成员从其 Membership 中移除本组关系；不维护 GroupFilteredOutObjects（由 RemoveExclusionFilterTrait 等
// 在 trait 切换时统一处理；此处假设 ClearGroup 后调用方会接 DestroyGroup）。
void FNetObjectGroups::ClearGroup(FNetObjectGroupHandle GroupHandle)
{
	if (IsValidGroup(GroupHandle))
	{
		FNetObjectGroup& Group = Groups[GroupHandle.GetGroupIndex()];

		for (FInternalNetRefIndex InternalIndex : Group.Members)
		{
			checkSlow(IsMemberOf(GroupMemberships[InternalIndex], GroupHandle));
			GroupMemberships[InternalIndex].RemoveMembership(GroupHandle);
		}

		Group.Members.Empty();
	}
}

// ---------- Group 访问辅助 ----------
const FNetObjectGroup* FNetObjectGroups::GetGroup(FNetObjectGroupHandle GroupHandle) const
{
	return IsValidGroup(GroupHandle) ? &Groups[GroupHandle.GetGroupIndex()] : nullptr;
}

FNetObjectGroup* FNetObjectGroups::GetGroup(FNetObjectGroupHandle GroupHandle)
{
	return IsValidGroup(GroupHandle) ? &Groups[GroupHandle.GetGroupIndex()] : nullptr;
}

const FNetObjectGroup* FNetObjectGroups::GetGroupFromIndex(FNetObjectGroupHandle::FGroupIndexType GroupIndex) const
{
	return (GroupIndex != FNetObjectGroupHandle::InvalidNetObjectGroupIndex && Groups.IsValidIndex(GroupIndex)) ? &Groups[GroupIndex] : nullptr;
}

FNetObjectGroup* FNetObjectGroups::GetGroupFromIndex(FNetObjectGroupHandle::FGroupIndexType GroupIndex)
{
	return (GroupIndex != FNetObjectGroupHandle::InvalidNetObjectGroupIndex && Groups.IsValidIndex(GroupIndex)) ? &Groups[GroupIndex] : nullptr;
}

FNetObjectGroupHandle FNetObjectGroups::GetHandleFromGroup(const FNetObjectGroup* InGroup) const
{
	check(InGroup);
	return FNetObjectGroupHandle(GetIndexFromGroup(InGroup), CurrentEpoch, InGroup->GroupId);
}

// 是否成员：先验证 Group 存在；再用对象级 GroupMemberships 做反查（O(NumGroupsForThisObject)）。
bool FNetObjectGroups::Contains(FNetObjectGroupHandle GroupHandle, FInternalNetRefIndex InternalIndex) const
{
	// If the group does not exist we cannot be in it..
	const FNetObjectGroup* Group = GetGroup(GroupHandle);
	if (!Group)
	{
		return false;
	}

	checkSlow(InternalIndex == 0U || (Group->Members.Contains(InternalIndex) == IsMemberOf(GroupMemberships[InternalIndex], GroupHandle)));

	return InternalIndex ? IsMemberOf(GroupMemberships[InternalIndex], GroupHandle) : false;
}

// 加入：双向索引同步 + 若是 Filter Group 同时维护 GroupFilteredOutObjects 位 + 成员数巨大时 ensure 报错。
void FNetObjectGroups::AddToGroup(FNetObjectGroupHandle GroupHandle, FInternalNetRefIndex InternalIndex)
{
	if (InternalIndex == FNetRefHandleManager::InvalidInternalIndex) 
	{
		return;
	}
	
	FNetObjectGroup* Group = GetGroup(GroupHandle);
	if (!Group)
	{
		UE_LOG(LogIrisGroup, Warning, TEXT("FNetObjectGroups::AddToGroup received invalid group (Index: %u Id: %u). Cannot add %s to it."), GroupHandle.Index, GroupHandle.UniqueId, *NetRefHandleManager->PrintObjectFromIndex(InternalIndex));
		return;
	}

	UE_LOG(LogIrisGroup, Verbose, TEXT("FNetObjectGroups::AddToGroup Adding %s to Group %s (Index: %u Id: %u)"),
		*NetRefHandleManager->PrintObjectFromIndex(InternalIndex), *GetGroupName(GroupHandle).ToString(), GroupHandle.Index, GroupHandle.UniqueId);

	FNetObjectGroupMembership& Membership = GroupMemberships[InternalIndex];
	if (AddGroupMembership(Membership, GroupHandle))
	{
		Group->Members.AddUnique(InternalIndex);

		if (IsFilterGroup(*Group))
		{
			GroupFilteredOutObjects.SetBit(InternalIndex);
		}

		if (CVarEnsureIfNumGroupMembershipsExceedsNum > 0 && Membership.NumMemberships() > CVarEnsureIfNumGroupMembershipsExceedsNum)
		{
			UE_LOG(LogIrisGroup, Error, TEXT("FNetObjectGroups::AddGroupMembership Unexpected high num groupmemberships for group %s (Index: %u Id: %u) NetObject %s is member of %d groups."),
				*GetGroupName(GroupHandle).ToString(), GroupHandle.Index, GroupHandle.UniqueId, *NetRefHandleManager->PrintObjectFromIndex(InternalIndex), Membership.NumMemberships());
			ensure(false);
		}
	}
}

// 移出：对称双向移除 + 必要时清 GroupFilteredOutObjects 位（仅当对象不再属于任何 Filter Group 时）。
void FNetObjectGroups::RemoveFromGroup(FNetObjectGroupHandle GroupHandle, FInternalNetRefIndex InternalIndex)
{
	if (InternalIndex == FNetRefHandleManager::InvalidInternalIndex)
	{
		return;
	}

	FNetObjectGroup* Group = GetGroup(GroupHandle);
	if (!Group)
	{
		UE_LOG(LogIrisGroup, Warning, TEXT("FNetObjectGroups::RemoveFromGroup received invalid group (Index: %u Id: %u). Cannot remove %s from it."), GroupHandle.Index, GroupHandle.UniqueId, *NetRefHandleManager->PrintObjectFromIndex(InternalIndex));
		return;
	}

	UE_LOG(LogIrisGroup, Verbose, TEXT("FNetObjectGroups::RemoveFromGroup Removing %s from Group %s (Index: %u Id: %u)"),
		*NetRefHandleManager->PrintObjectFromIndex(InternalIndex), *GetGroupName(GroupHandle).ToString(), GroupHandle.Index, GroupHandle.UniqueId);

	FNetObjectGroupMembership& GroupMembership = GroupMemberships[InternalIndex];
	checkSlow(IsMemberOf(GroupMembership, GroupHandle));

	GroupMembership.RemoveMembership(GroupHandle);
	Group->Members.RemoveSingle(InternalIndex);

	// Check to see if the object is still part of a filter group
	if (!IsInAnyFilterGroup(GroupMembership))
	{
		GroupFilteredOutObjects.ClearBit(InternalIndex);
	}
}

// 加 Exclusion trait：若 Group 之前不是 Filter 组，把所有现成员的 GroupFilteredOutObjects 位置 1。
void FNetObjectGroups::AddExclusionFilterTrait(FNetObjectGroupHandle GroupHandle)
{
	if (FNetObjectGroup* Group = GetGroup(GroupHandle))
	{
		if (!IsFilterGroup(*Group))
		{
			UE_LOG(LogIrisGroup, Verbose, TEXT("FNetObjectGroups::AddExclusionFilterTrait to Group %s (GroupIndex: %u)"), *GetGroupName(GroupHandle).ToString(), GroupHandle.GetGroupIndex());

			Group->Traits |= ENetObjectGroupTraits::IsExclusionFiltering;

			// Flag all current members of this group that they are now filterable
			for (FInternalNetRefIndex MemberIndex : Group->Members)
			{
				GroupFilteredOutObjects.SetBit(MemberIndex);
			}
		}
	}
}

// 移除 Exclusion trait：清 trait 后，对每个成员判定是否还属于其它 Filter Group，否则清 GroupFilteredOutObjects 位。
void FNetObjectGroups::RemoveExclusionFilterTrait(FNetObjectGroupHandle GroupHandle)
{
	FNetObjectGroup* Group = GetGroup(GroupHandle);
	if (Group == nullptr)
	{
		return;
	}

	if (!IsExclusionFilterGroup(*Group))
	{
		return;
	}

	UE_LOG(LogIrisGroup, Verbose, TEXT("FNetObjectGroups::RemoveExclusionFilterTrait to Group %s (GroupIndex: %u)"), *GetGroupName(GroupHandle).ToString(), GroupHandle.GetGroupIndex());

	Group->Traits &= ~(ENetObjectGroupTraits::IsExclusionFiltering);

	for (FInternalNetRefIndex MemberIndex : Group->Members)
	{
		// Check to see if the object is still part of a filter group
		if (!IsInAnyFilterGroup(GroupMemberships[MemberIndex]))
		{
			GroupFilteredOutObjects.ClearBit(MemberIndex);
		}
	}
}

// 加 Inclusion trait：仅当 Group 没有任何 Filter trait 时才设置（"Inclusion 与 Exclusion 互斥"约束）。
// 注意：此处不维护 GroupFilteredOutObjects——Inclusion Group 使用更上层 FReplicationFiltering 的位图。
void FNetObjectGroups::AddInclusionFilterTrait(FNetObjectGroupHandle GroupHandle)
{
	if (FNetObjectGroup* Group = GetGroup(GroupHandle))
	{
		// Can't be both inclusion and exclusion so let's do nothing if the group has any sort of filter trait.
		if (!IsFilterGroup(*Group))
		{
			Group->Traits |= ENetObjectGroupTraits::IsInclusionFiltering;
		}
	}
}

// 取消 Inclusion trait：仅清 trait 位（GroupFilteredOutObjects 不需要维护，参见上注）。
void FNetObjectGroups::RemoveInclusionFilterTrait(FNetObjectGroupHandle GroupHandle)
{
	FNetObjectGroup* Group = GetGroup(GroupHandle);
	if (Group == nullptr)
	{
		return;
	}

	// Simply remove the trait.
	Group->Traits &= ~(ENetObjectGroupTraits::IsInclusionFiltering);
}

bool FNetObjectGroups::IsFilterGroup(FNetObjectGroupHandle GroupHandle) const
{
	if (const FNetObjectGroup* Group = GetGroup(GroupHandle))
	{
		return EnumHasAnyFlags(Group->Traits, ENetObjectGroupTraits::IsExclusionFiltering | ENetObjectGroupTraits::IsInclusionFiltering);
	}

	return false;
}

// 用对象 Membership 的 Group Index 列表去查每个 Group 的 trait。早返回。
bool FNetObjectGroups::IsInAnyFilterGroup(const FNetObjectGroupMembership& GroupMembership) const
{
	for (FNetObjectGroupHandle::FGroupIndexType AssignedGroupIndex : GroupMembership.GetGroupIndexes())
	{
		if (const FNetObjectGroup* Group = GetGroupFromIndex(AssignedGroupIndex))
		{
			if (IsFilterGroup(*Group))
			{
				return true;
			}
		}
	}

	return false;
}

// 取对象所属 Group Index 列表（视图，零拷贝）。
const TArrayView<const FNetObjectGroupHandle::FGroupIndexType> FNetObjectGroups::GetGroupIndexesOfNetObject(FInternalNetRefIndex InternalIndex) const
{
	if (ensure(GroupMemberships.IsValidIndex(InternalIndex)))
	{
		return GroupMemberships[InternalIndex].GetGroupIndexes();
	}

	return TArrayView<const FNetObjectGroupHandle::FGroupIndexType>();
}

// 取对象所属 Group Handle 列表：内部按 Index → Handle 转换（含 Epoch + UniqueId）。
void FNetObjectGroups::GetGroupHandlesOfNetObject(FInternalNetRefIndex InternalIndex, TArray<FNetObjectGroupHandle>& OutHandles) const
{
	if (ensure(GroupMemberships.IsValidIndex(InternalIndex)))
	{
		const TArrayView<const FNetObjectGroupHandle::FGroupIndexType> GroupIndexes = GroupMemberships[InternalIndex].GetGroupIndexes();
		OutHandles.Reserve(GroupIndexes.Num());

		for (FNetObjectGroupHandle::FGroupIndexType AssignedGroupIndex : GroupIndexes)
		{
			OutHandles.Add(GetHandleFromIndex(AssignedGroupIndex));
		}
	}
}

bool FNetObjectGroups::IsMemberOf(const FNetObjectGroupMembership& Target, FNetObjectGroupHandle Group)
{
	return Target.ContainsMembership(Group);
}

bool FNetObjectGroups::AddGroupMembership(FNetObjectGroupMembership& Target, FNetObjectGroupHandle Group)
{
	if (!Target.ContainsMembership(Group))
	{
		Target.AddMembership(Group);

		return true;
	}

	return false;
}

void FNetObjectGroups::ResetGroupMembership(FNetObjectGroupMembership& Target)
{
	Target.ResetMemberships();
}

void FNetObjectGroups::Init(const FNetObjectGroupInitParams& Params)
{
	NetRefHandleManager = Params.NetRefHandleManager;

	ensureMsgf(Params.MaxGroupCount <= FNetObjectGroupHandle::MaxGroupIndexCount, TEXT("MaxGroupCount cannot exceed %u"), FNetObjectGroupHandle::MaxGroupIndexCount);
	MaxGroupCount = FMath::Clamp<uint32>(Params.MaxGroupCount, 0U, FNetObjectGroupHandle::MaxGroupIndexCount);

	// Reserve first as invalid group
	Groups.Add(FNetObjectGroup());

	GroupMemberships.SetNum(Params.MaxInternalNetRefIndex);
	GroupFilteredOutObjects.Init(Params.MaxInternalNetRefIndex);
}

void FNetObjectGroups::OnMaxInternalNetRefIndexIncreased(FInternalNetRefIndex NewMaxInternalIndex)
{
	GroupMemberships.SetNum(NewMaxInternalIndex);
	GroupFilteredOutObjects.SetNumBits(NewMaxInternalIndex);
}

FNetObjectGroupHandle FNetObjectGroups::CreateGroup(FName InGroupName)
{
	const bool bCanCreateGroup = (uint32)Groups.Num() < MaxGroupCount;

	if (!bCanCreateGroup)
	{
		UE_LOG(LogIrisGroup, Warning, TEXT("Maximum allowed groups allocated: %u. Group: %s cannot be created"), MaxGroupCount, *InGroupName.ToString());
		ensureMsgf(false, TEXT("FNetObjectGroups::CreateGroup: Maximum allowed groups allocated."));
		return FNetObjectGroupHandle();
	}

	// Auto-generate a name if none was passed	
	if (InGroupName == NAME_None)
	{
		InGroupName = FName(TEXT("NetObjectGroup"), AutogeneratedGroupNameId++);
	}

	// Validate that the given name is unique
	{
		const FNetObjectGroupHandle ExistingGroup = FindGroupHandle(InGroupName);
		if (ExistingGroup.IsValid())
		{
			UE_LOG(LogIrisGroup, Warning, TEXT("Tried to create a group named: %s. But this name was already registered to groupHandle: %u"), *InGroupName.ToString(), ExistingGroup.GetGroupIndex());
			ensureMsgf(false, TEXT("FNetObjectGroups::CreateGroup: Group name %s is already registered"), *InGroupName.ToString());
			return FNetObjectGroupHandle();
		}
		
	}

	const uint32 NewGroupId = NextGroupUniqueId++;
	
	const uint32 Index = (uint32)Groups.Emplace(FNetObjectGroup{.GroupName = InGroupName, .GroupId = NewGroupId});

	UE_LOG(LogIrisGroup, Verbose, TEXT("Created GroupHandle named: %s Index: %u Id: %u"), *InGroupName.ToString(), Index, NewGroupId);

	FNetObjectGroupHandle GroupHandle;
	GroupHandle.Index = static_cast<FNetObjectGroupHandle::FGroupIndexType>(Index);
	GroupHandle.Epoch = CurrentEpoch;
	GroupHandle.UniqueId = NewGroupId;

	ensureMsgf(NextGroupUniqueId != 0, TEXT("We created more than MAX_uint32 unique NetGroups. An Id overflow occured and it may cause conflicts with existing handles."));

	return GroupHandle;
}

void FNetObjectGroups::DestroyGroup(FNetObjectGroupHandle GroupHandle)
{
	if (IsValidGroup(GroupHandle))
	{
		FNetObjectGroup& Group = Groups[GroupHandle.GetGroupIndex()];

		UE_LOG(LogIrisGroup, Verbose, TEXT("Destroyed GroupHandle named: %s Index: %u Id: %u"), *Group.GroupName.ToString(), GroupHandle.Index, Group.GroupId);

		ClearGroup(GroupHandle);		
		Groups.RemoveAt(GroupHandle.GetGroupIndex());
	}
}

void FNetObjectGroups::ClearGroup(FNetObjectGroupHandle GroupHandle)
{
	if (IsValidGroup(GroupHandle))
	{
		FNetObjectGroup& Group = Groups[GroupHandle.GetGroupIndex()];

		for (FInternalNetRefIndex InternalIndex : Group.Members)
		{
			checkSlow(IsMemberOf(GroupMemberships[InternalIndex], GroupHandle));
			GroupMemberships[InternalIndex].RemoveMembership(GroupHandle);
		}

		Group.Members.Empty();
	}
}

const FNetObjectGroup* FNetObjectGroups::GetGroup(FNetObjectGroupHandle GroupHandle) const
{
	return IsValidGroup(GroupHandle) ? &Groups[GroupHandle.GetGroupIndex()] : nullptr;
}

FNetObjectGroup* FNetObjectGroups::GetGroup(FNetObjectGroupHandle GroupHandle)
{
	return IsValidGroup(GroupHandle) ? &Groups[GroupHandle.GetGroupIndex()] : nullptr;
}

const FNetObjectGroup* FNetObjectGroups::GetGroupFromIndex(FNetObjectGroupHandle::FGroupIndexType GroupIndex) const
{
	return (GroupIndex != FNetObjectGroupHandle::InvalidNetObjectGroupIndex && Groups.IsValidIndex(GroupIndex)) ? &Groups[GroupIndex] : nullptr;
}

FNetObjectGroup* FNetObjectGroups::GetGroupFromIndex(FNetObjectGroupHandle::FGroupIndexType GroupIndex)
{
	return (GroupIndex != FNetObjectGroupHandle::InvalidNetObjectGroupIndex && Groups.IsValidIndex(GroupIndex)) ? &Groups[GroupIndex] : nullptr;
}

FNetObjectGroupHandle FNetObjectGroups::GetHandleFromGroup(const FNetObjectGroup* InGroup) const
{
	check(InGroup);
	return FNetObjectGroupHandle(GetIndexFromGroup(InGroup), CurrentEpoch, InGroup->GroupId);
}

bool FNetObjectGroups::Contains(FNetObjectGroupHandle GroupHandle, FInternalNetRefIndex InternalIndex) const
{
	// If the group does not exist we cannot be in it..
	const FNetObjectGroup* Group = GetGroup(GroupHandle);
	if (!Group)
	{
		return false;
	}

	checkSlow(InternalIndex == 0U || (Group->Members.Contains(InternalIndex) == IsMemberOf(GroupMemberships[InternalIndex], GroupHandle)));

	return InternalIndex ? IsMemberOf(GroupMemberships[InternalIndex], GroupHandle) : false;
}

void FNetObjectGroups::AddToGroup(FNetObjectGroupHandle GroupHandle, FInternalNetRefIndex InternalIndex)
{
	if (InternalIndex == FNetRefHandleManager::InvalidInternalIndex) 
	{
		return;
	}
	
	FNetObjectGroup* Group = GetGroup(GroupHandle);
	if (!Group)
	{
		UE_LOG(LogIrisGroup, Warning, TEXT("FNetObjectGroups::AddToGroup received invalid group (Index: %u Id: %u). Cannot add %s to it."), GroupHandle.Index, GroupHandle.UniqueId, *NetRefHandleManager->PrintObjectFromIndex(InternalIndex));
		return;
	}

	UE_LOG(LogIrisGroup, Verbose, TEXT("FNetObjectGroups::AddToGroup Adding %s to Group %s (Index: %u Id: %u)"),
		*NetRefHandleManager->PrintObjectFromIndex(InternalIndex), *GetGroupName(GroupHandle).ToString(), GroupHandle.Index, GroupHandle.UniqueId);

	FNetObjectGroupMembership& Membership = GroupMemberships[InternalIndex];
	if (AddGroupMembership(Membership, GroupHandle))
	{
		Group->Members.AddUnique(InternalIndex);

		if (IsFilterGroup(*Group))
		{
			GroupFilteredOutObjects.SetBit(InternalIndex);
		}

		if (CVarEnsureIfNumGroupMembershipsExceedsNum > 0 && Membership.NumMemberships() > CVarEnsureIfNumGroupMembershipsExceedsNum)
		{
			UE_LOG(LogIrisGroup, Error, TEXT("FNetObjectGroups::AddGroupMembership Unexpected high num groupmemberships for group %s (Index: %u Id: %u) NetObject %s is member of %d groups."),
				*GetGroupName(GroupHandle).ToString(), GroupHandle.Index, GroupHandle.UniqueId, *NetRefHandleManager->PrintObjectFromIndex(InternalIndex), Membership.NumMemberships());
			ensure(false);
		}
	}
}

void FNetObjectGroups::RemoveFromGroup(FNetObjectGroupHandle GroupHandle, FInternalNetRefIndex InternalIndex)
{
	if (InternalIndex == FNetRefHandleManager::InvalidInternalIndex)
	{
		return;
	}

	FNetObjectGroup* Group = GetGroup(GroupHandle);
	if (!Group)
	{
		UE_LOG(LogIrisGroup, Warning, TEXT("FNetObjectGroups::RemoveFromGroup received invalid group (Index: %u Id: %u). Cannot remove %s from it."), GroupHandle.Index, GroupHandle.UniqueId, *NetRefHandleManager->PrintObjectFromIndex(InternalIndex));
		return;
	}

	UE_LOG(LogIrisGroup, Verbose, TEXT("FNetObjectGroups::RemoveFromGroup Removing %s from Group %s (Index: %u Id: %u)"),
		*NetRefHandleManager->PrintObjectFromIndex(InternalIndex), *GetGroupName(GroupHandle).ToString(), GroupHandle.Index, GroupHandle.UniqueId);

	FNetObjectGroupMembership& GroupMembership = GroupMemberships[InternalIndex];
	checkSlow(IsMemberOf(GroupMembership, GroupHandle));

	GroupMembership.RemoveMembership(GroupHandle);
	Group->Members.RemoveSingle(InternalIndex);

	// Check to see if the object is still part of a filter group
	if (!IsInAnyFilterGroup(GroupMembership))
	{
		GroupFilteredOutObjects.ClearBit(InternalIndex);
	}
}

void FNetObjectGroups::AddExclusionFilterTrait(FNetObjectGroupHandle GroupHandle)
{
	if (FNetObjectGroup* Group = GetGroup(GroupHandle))
	{
		if (!IsFilterGroup(*Group))
		{
			UE_LOG(LogIrisGroup, Verbose, TEXT("FNetObjectGroups::AddExclusionFilterTrait to Group %s (GroupIndex: %u)"), *GetGroupName(GroupHandle).ToString(), GroupHandle.GetGroupIndex());

			Group->Traits |= ENetObjectGroupTraits::IsExclusionFiltering;

			// Flag all current members of this group that they are now filterable
			for (FInternalNetRefIndex MemberIndex : Group->Members)
			{
				GroupFilteredOutObjects.SetBit(MemberIndex);
			}
		}
	}
}

void FNetObjectGroups::RemoveExclusionFilterTrait(FNetObjectGroupHandle GroupHandle)
{
	FNetObjectGroup* Group = GetGroup(GroupHandle);
	if (Group == nullptr)
	{
		return;
	}

	if (!IsExclusionFilterGroup(*Group))
	{
		return;
	}

	UE_LOG(LogIrisGroup, Verbose, TEXT("FNetObjectGroups::RemoveExclusionFilterTrait to Group %s (GroupIndex: %u)"), *GetGroupName(GroupHandle).ToString(), GroupHandle.GetGroupIndex());

	Group->Traits &= ~(ENetObjectGroupTraits::IsExclusionFiltering);

	for (FInternalNetRefIndex MemberIndex : Group->Members)
	{
		// Check to see if the object is still part of a filter group
		if (!IsInAnyFilterGroup(GroupMemberships[MemberIndex]))
		{
			GroupFilteredOutObjects.ClearBit(MemberIndex);
		}
	}
}

void FNetObjectGroups::AddInclusionFilterTrait(FNetObjectGroupHandle GroupHandle)
{
	if (FNetObjectGroup* Group = GetGroup(GroupHandle))
	{
		// Can't be both inclusion and exclusion so let's do nothing if the group has any sort of filter trait.
		if (!IsFilterGroup(*Group))
		{
			Group->Traits |= ENetObjectGroupTraits::IsInclusionFiltering;
		}
	}
}

void FNetObjectGroups::RemoveInclusionFilterTrait(FNetObjectGroupHandle GroupHandle)
{
	FNetObjectGroup* Group = GetGroup(GroupHandle);
	if (Group == nullptr)
	{
		return;
	}

	// Simply remove the trait.
	Group->Traits &= ~(ENetObjectGroupTraits::IsInclusionFiltering);
}

bool FNetObjectGroups::IsFilterGroup(FNetObjectGroupHandle GroupHandle) const
{
	if (const FNetObjectGroup* Group = GetGroup(GroupHandle))
	{
		return EnumHasAnyFlags(Group->Traits, ENetObjectGroupTraits::IsExclusionFiltering | ENetObjectGroupTraits::IsInclusionFiltering);
	}

	return false;
}

bool FNetObjectGroups::IsInAnyFilterGroup(const FNetObjectGroupMembership& GroupMembership) const
{
	for (FNetObjectGroupHandle::FGroupIndexType AssignedGroupIndex : GroupMembership.GetGroupIndexes())
	{
		if (const FNetObjectGroup* Group = GetGroupFromIndex(AssignedGroupIndex))
		{
			if (IsFilterGroup(*Group))
			{
				return true;
			}
		}
	}

	return false;
}

const TArrayView<const FNetObjectGroupHandle::FGroupIndexType> FNetObjectGroups::GetGroupIndexesOfNetObject(FInternalNetRefIndex InternalIndex) const
{
	if (ensure(GroupMemberships.IsValidIndex(InternalIndex)))
	{
		return GroupMemberships[InternalIndex].GetGroupIndexes();
	}

	return TArrayView<const FNetObjectGroupHandle::FGroupIndexType>();
}

void FNetObjectGroups::GetGroupHandlesOfNetObject(FInternalNetRefIndex InternalIndex, TArray<FNetObjectGroupHandle>& OutHandles) const
{
	if (ensure(GroupMemberships.IsValidIndex(InternalIndex)))
	{
		const TArrayView<const FNetObjectGroupHandle::FGroupIndexType> GroupIndexes = GroupMemberships[InternalIndex].GetGroupIndexes();
		OutHandles.Reserve(GroupIndexes.Num());

		for (FNetObjectGroupHandle::FGroupIndexType AssignedGroupIndex : GroupIndexes)
		{
			OutHandles.Add(GetHandleFromIndex(AssignedGroupIndex));
		}
	}
}

} // end namespace UE::Net::Private
