// Copyright Epic Games, Inc. All Rights Reserved.
#pragma once

// ============================================================================
// 文件概览：LinkGenerationConfig.h
// ----------------------------------------------------------------------------
// 定义"自动生成跳跃 NavLink"所需的参数结构（实验性）。
// 主要类型：
//   - FNavLinkGenerationJumpConfig：新结构（5.6+），支持上行/下行不同 Area；
//   - FNavLinkGenerationJumpDownConfig：旧结构（5.7 弃用），保留仅为兼容加载。
// 使用位置：ARecastNavMesh 可以配置多个 FNavLinkGenerationJumpConfig；
//   FRecastTileGenerator 在 Tile 构建阶段沿边缘采样落点，
//   调用底层 dtNavLinkBuilderJumpConfig（Detour NavLink 构建器）产生 OffMeshConnection。
// 坐标说明：所有参数均以 UE 世界单位（cm）给出，Copy 到 Detour 结构时会按需转换。
// ============================================================================

#include "Templates/SubclassOf.h"
#include "AI/Navigation/NavigationTypes.h"

#include "LinkGenerationConfig.generated.h"

class UBaseGeneratedNavLinksProxy;
class UNavAreaBase;

#if WITH_RECAST
struct dtNavLinkBuilderJumpConfig;
#endif //WITH_RECAST

// Link 构建方式位掩码
UENUM(meta = (Bitflags, UseEnumValuesAsMaskValuesInEditor = "true"))
enum class ENavLinkBuilderFlags : uint16
{
	CreateCenterPointLink		= 1 << 0,   // 在边的中点创建一条 Link（最常用）
	CreateExtremityLink			= 1 << 1,   // 在边的两个端点额外创建 Link（可覆盖更宽入口）
};
ENUM_CLASS_FLAGS(ENavLinkBuilderFlags);

/** Experimental configuration to generate vertical links. */
// 自动跳跃 Link 生成配置；一个 ARecastNavMesh 可挂多条（例如"短跳""长跳"分别一套参数）
USTRUCT()
struct FNavLinkGenerationJumpConfig
{
	GENERATED_BODY()

	NAVIGATIONSYSTEM_API FNavLinkGenerationJumpConfig();

	// Note: We need to explicitly disable warnings on these constructors/operators for clang to be happy with deprecated variables
	PRAGMA_DISABLE_DEPRECATION_WARNINGS
	~FNavLinkGenerationJumpConfig() = default;
	FNavLinkGenerationJumpConfig(const FNavLinkGenerationJumpConfig&) = default;
	FNavLinkGenerationJumpConfig(FNavLinkGenerationJumpConfig&&) = default;
	FNavLinkGenerationJumpConfig& operator=(const FNavLinkGenerationJumpConfig&) = default;
	FNavLinkGenerationJumpConfig& operator=(FNavLinkGenerationJumpConfig&&) = default;
	PRAGMA_ENABLE_DEPRECATION_WARNINGS

	/** Should this config be used to generate links. */
	// 是否启用本条配置；关掉可以临时停用但保留参数
	UPROPERTY(EditAnywhere, Config, Category = Settings)
	bool bEnabled = true;

	/** A name for this config */
	// 仅用于在编辑器/日志中识别；不参与运行时逻辑
	UPROPERTY(EditAnywhere, Config, Category = Settings)
	FName Name;
	
	/** Horizontal length of the jump.
	 * How far from the starting point we will look for ground. */ 
	// 跳跃的水平距离（从边缘出发寻找落地点的最远水平射程）
	UPROPERTY(EditAnywhere, Config, Category = Settings, meta=(UIMin=0, ClampMin=0))
	float JumpLength = 150.f; 

	/** How far from the navmesh edge is the jump started. */
	// Link 起点相对 NavMesh 边缘的水平内缩距离，避免 Agent 贴边起跳
	UPROPERTY(EditAnywhere, Config, Category = Settings, meta=(UIMin=0, ClampMin=0))
	float JumpDistanceFromEdge = 10.f; 

	/** How far below the starting height we want to look for landing ground.
	 * A negative value can be used to generate a trajectory landing above the starting height
	 * (if negative, make sure to use a JumpHeight value big enough).
	 */
	// 最大下落深度；正值代表向下看多远，负值代表只找高于起点的落点（需要配合足够大的 JumpHeight）
	UPROPERTY(EditAnywhere, Config, Category = Settings)
	float JumpMaxDepth = 150.f;

	/** Peak height relative to the height of the starting point. */
	// 跳跃抛物线顶点相对起点的高度
	UPROPERTY(EditAnywhere, Config, Category = Settings, meta=(UIMin=0, ClampMin=0))
	float JumpHeight = 50.f;

	/** Tolerance at both ends of the jump to find ground. */
	// 起止点吸附地面时允许的垂直容差
	UPROPERTY(EditAnywhere, Config, Category = Settings, meta=(UIMin=0, ClampMin=0))
	float JumpEndsHeightTolerance = 80.f;

	/** Value multiplied by CellSize to find the distance between sampling trajectories. Default is 1.
     *  Larger values improve generation speed but might introduce sampling errors.  */
	// 采样间距倍率（乘 CellSize）。越大生成越快，但可能漏掉精细落点
	UPROPERTY(EditAnywhere, Config, Category = Settings, meta=(UIMin=1, ClampMin=1))
	float SamplingSeparationFactor = 1.f;
	
	/** When filtering similar links, it's the distance used to compare between segment endpoints to match similar links.
	 * Use greater distance for more filtering (0 to deactivate filtering). */
	// 相似 Link 过滤阈值：若两条 Link 端点间距离小于此值则判为重复，只保留一条。0 表示不过滤。
	UPROPERTY(EditAnywhere, Config, Category = Settings, meta=(UIMin=0, ClampMin=0))
	float FilterDistanceThreshold = 80.f;

	/** Flags used to indicate how links will be added. */
	// ENavLinkBuilderFlags 位掩码：决定在边的中点/端点生成 Link
	UPROPERTY(EditAnywhere, Config, Category = Settings, meta = (Bitmask, BitmaskEnum = "/Script/NavigationSystem.ENavLinkBuilderFlags"))
	uint16 LinkBuilderFlags = (uint16)ENavLinkBuilderFlags::CreateCenterPointLink;

#if WITH_EDITORONLY_DATA
	/** Area class for links generated by this configuration. */
	// 5.6 弃用：统一 Area 改成上/下方向分离配置，详见 DownDirectionAreaClass / UpDirectionAreaClass
	UE_DEPRECATED(5.6, "AreaClass is deprecated")
	UPROPERTY(Config, meta = (DeprecatedProperty, DeprecationMessage = "Use DownDirectionAreaClass and UpDirectionAreaClass instead."))
	TSubclassOf<UNavAreaBase> AreaClass_DEPRECATED;
#endif //WITH_EDITORONLY_DATA

	/**
	 * Area class for downward traversal of links generated by this configuration.
	 * @note If the value matches UpDirectionAreaClass, a single bidirectional link will be used to represent links generated by this configuration.
	 * If the value is null, no link will be generated in this direction
	 */
	// 下跳方向使用的 Area 类；null 则不生成下向 Link；与 UpDirectionAreaClass 相同则生成双向 Link
	UPROPERTY(EditAnywhere, Config, Category = Settings)
	TSubclassOf<UNavAreaBase> DownDirectionAreaClass;

	/**
	 * Area class for upward traversal of links generated by this configuration.
	 * @note If the value matches DownDirectionAreaClass, a single bidirectional link will be used to represent links generated by this configuration.
	 * If the value is null, no link will be generated in this direction
	 */
	// 上跳方向使用的 Area 类；用法同上
	UPROPERTY(EditAnywhere, Config, Category = Settings)
	TSubclassOf<UNavAreaBase> UpDirectionAreaClass;

	/** Class used to handle links made with this configuration.
	 * Using this allows to implement custom behaviors when using navlinks, for example during the pathfollow.
	 * Note that having a proxy is not required for successful navlink pathfinding,
	 * but it does allow for custom behavior at the start and the end of a given navlink.
	 * This implies that using LinkProxyClass is optional, and it can remain empty (the default value).
	 * @see INavLinkCustomInterface 
	 * @see UGeneratedNavLinksProxy
	 */
	// 可选：本 Config 生成的所有 Link 共享的"代理 UObject 类"；
	// 若指定，则运行时实例化一个 Proxy 并注册到 CustomNavLinksMap，从而可以实现
	// OnLinkMoveStarted / IsLinkPathfindingAllowed 之类的行为。
	UPROPERTY(EditAnywhere, Category= Settings)
	TSubclassOf<UBaseGeneratedNavLinksProxy> LinkProxyClass;

	/** Identifier used identify the current proxy handler. All links generated through this config will use the same handler. */
	// Proxy 的稳定 64 位 ID；本 Config 生成的所有 Link 都挂此 ID
	UPROPERTY()
	FNavLinkId LinkProxyId;

	/** Current proxy. The proxy instance is build from the LinkProxyClass (provided it's not null).
	 * A proxy will be created if a @see LinkProxyClass is used.
	 */
	// 运行时创建的 Proxy 实例；Transient 表示不序列化
	UPROPERTY(Transient)
	TObjectPtr<UBaseGeneratedNavLinksProxy> LinkProxy = nullptr;

	/** Is the link proxy registered to the navigation system CustomNavLinksMap.
	 * Registration occurs on PostRegisterAllComponents or on PostLoadPreRebuild if a new proxy was created. */
	// 防止重复注册 CustomNavLinksMap
	UPROPERTY(Transient)
	bool bLinkProxyRegistered = false;

	/** Implemented for deprecated property cleanup purposes. */
	// 自定义序列化；主要负责在加载时把弃用字段（如 AreaClass_DEPRECATED）迁移到新字段
	bool Serialize(FArchive& Ar);

#if WITH_RECAST	
	/** Copy configuration to dtNavLinkBuilderJumpConfig. */
	// 参数拷贝到 Detour NavLink 构建器结构；此处完成 UE cm → Recast 单位的换算
	void CopyToDetourConfig(dtNavLinkBuilderJumpConfig& OutDetourConfig) const;
#endif //WITH_RECAST
};

// 让 FNavLinkGenerationJumpConfig 走自定义 Serialize 路径
template<> struct TStructOpsTypeTraits<FNavLinkGenerationJumpConfig> : public TStructOpsTypeTraitsBase2<FNavLinkGenerationJumpConfig>
{
	enum
	{
		WithSerializer = true
	};
};


PRAGMA_DISABLE_DEPRECATION_WARNINGS
struct dtNavLinkBuilderJumpDownConfig;

/** Experimental configuration to generate vertical links. */
// 旧版"仅下跳"配置结构；5.7 起替换为 FNavLinkGenerationJumpConfig（支持双向）。
// 目前仅为老存档反序列化保留；字段语义同上。
USTRUCT()
struct UE_DEPRECATED(5.7, "Use FNavLinkGenerationJumpConfig instead.") FNavLinkGenerationJumpDownConfig
{
	GENERATED_BODY()

	FNavLinkGenerationJumpDownConfig();

	// Note: We need to explicitly disable warnings on these constructors/operators for clang to be happy with deprecated variables
	~FNavLinkGenerationJumpDownConfig() = default;
	FNavLinkGenerationJumpDownConfig(const FNavLinkGenerationJumpDownConfig&) = default;
	FNavLinkGenerationJumpDownConfig(FNavLinkGenerationJumpDownConfig&&) = default;
	FNavLinkGenerationJumpDownConfig& operator=(const FNavLinkGenerationJumpDownConfig&) = default;
	FNavLinkGenerationJumpDownConfig& operator=(FNavLinkGenerationJumpDownConfig&&) = default;

	/** Should this config be used to generate links. */
	UPROPERTY(Config)		// @todo Hidden for now. Since there is currently only one config, it has no real usage.
	bool bEnabled = true;
	
	/** Horizontal length of the jump.
	 * How far from the starting point we will look for ground. */ 
	UPROPERTY(EditAnywhere, Config, Category = Settings, meta=(UIMin=0, ClampMin=0))
	float JumpLength = 150.f; 

	/** How far from the navmesh edge is the jump started. */
	UPROPERTY(EditAnywhere, Config, Category = Settings, meta=(UIMin=0, ClampMin=0))
	float JumpDistanceFromEdge = 10.f; 

	/** How far below the starting height we want to look for landing ground. */
	UPROPERTY(EditAnywhere, Config, Category = Settings, meta=(UIMin=0, ClampMin=0))
	float JumpMaxDepth = 150.f;

	/** Peak height relative to the height of the starting point. */
	UPROPERTY(EditAnywhere, Config, Category = Settings, meta=(UIMin=0, ClampMin=0))
	float JumpHeight = 50.f;

	/** Tolerance at both ends of the jump to find ground. */
	UPROPERTY(EditAnywhere, Config, Category = Settings, meta=(UIMin=0, ClampMin=0))
	float JumpEndsHeightTolerance = 80.f;

	/** Value multiplied by CellSize to find the distance between sampling trajectories. Default is 1.
     *  Larger values improve generation speed but might introduce sampling errors.  */
	UPROPERTY(EditAnywhere, Config, Category = Settings, meta=(UIMin=1, ClampMin=1))
	float SamplingSeparationFactor = 1.f;
	
	/** When filtering similar links, it's the distance used to compare between segment endpoints to match similar links.
	 * Use greater distance for more filtering (0 to deactivate filtering). */
	UPROPERTY(EditAnywhere, Config, Category = Settings, meta=(UIMin=0, ClampMin=0))
	float FilterDistanceThreshold = 80.f;

	/** Flags used to indicate how links will be added. */
	UPROPERTY(EditAnywhere, Config, Category = Settings, meta = (Bitmask, BitmaskEnum = "/Script/NavigationSystem.ENavLinkBuilderFlags"))
	uint16 LinkBuilderFlags = (uint16)ENavLinkBuilderFlags::CreateCenterPointLink;

#if WITH_EDITORONLY_DATA
	/** Area class for links generated by this configuration. */
	UE_DEPRECATED(5.6, "AreaClass is deprecated")
	UPROPERTY(Config, meta = (DeprecatedProperty, DeprecationMessage = "Use DownDirectionAreaClass and UpDirectionAreaClass instead."))
	TSubclassOf<UNavAreaBase> AreaClass_DEPRECATED;
#endif //WITH_EDITORONLY_DATA

	/**
	 * Area class for downward traversal of links generated by this configuration.
	 * @note If the value matches UpDirectionAreaClass, a single bidirectional link will be used to represent links generated by this configuration.
	 * If the value is null, no link will be generated in this direction
	 */
	UPROPERTY(EditAnywhere, Config, Category = Settings)
	TSubclassOf<UNavAreaBase> DownDirectionAreaClass;

	/**
	 * Area class for upward traversal of links generated by this configuration.
	 * @note If the value matches DownDirectionAreaClass, a single bidirectional link will be used to represent links generated by this configuration.
	 * If the value is null, no link will be generated in this direction
	 */
	UPROPERTY(EditAnywhere, Config, Category = Settings)
	TSubclassOf<UNavAreaBase> UpDirectionAreaClass;

	/** Class used to handle links made with this configuration.
	 * Using this allows to implement custom behaviors when using navlinks, for example during the pathfollow.
	 * Note that having a proxy is not required for successful navlink pathfinding,
	 * but it does allow for custom behavior at the start and the end of a given navlink.
	 * This implies that using LinkProxyClass is optional, and it can remain empty (the default value).
	 * @see INavLinkCustomInterface 
	 * @see UGeneratedNavLinksProxy
	 */
	UPROPERTY(EditAnywhere, Category= Settings)
	TSubclassOf<UBaseGeneratedNavLinksProxy> LinkProxyClass;

	/** Identifier used identify the current proxy handler. All links generated through this config will use the same handler. */
	UPROPERTY()
	FNavLinkId LinkProxyId;

	/** Current proxy. The proxy instance is build from the LinkProxyClass (provided it's not null).
	 * A proxy will be created if a @see LinkProxyClass is used.
	 */
	UPROPERTY(Transient)
	TObjectPtr<UBaseGeneratedNavLinksProxy> LinkProxy = nullptr;

	/** Is the link proxy registered to the navigation system CustomNavLinksMap.
	 * Registration occurs on PostRegisterAllComponents or on PostLoadPreRebuild if a new proxy was created. */
	UPROPERTY(Transient)
	bool bLinkProxyRegistered = false;

	/** Implemented for deprecated property cleanup purposes. */
	bool Serialize(FArchive& Ar);

#if WITH_RECAST	
	/** Copy configuration to dtNavLinkBuilderJumpDownConfig. */
	void CopyToDetourConfig(dtNavLinkBuilderJumpDownConfig& OutDetourConfig) const;
#endif //WITH_RECAST
};

template<> struct TStructOpsTypeTraits<FNavLinkGenerationJumpDownConfig> : public TStructOpsTypeTraitsBase2<FNavLinkGenerationJumpDownConfig>
{
	enum
	{
		WithSerializer = true
	};
};
PRAGMA_ENABLE_DEPRECATION_WARNINGS
	GENERATED_BODY()

	NAVIGATIONSYSTEM_API FNavLinkGenerationJumpConfig();

	// Note: We need to explicitly disable warnings on these constructors/operators for clang to be happy with deprecated variables
	PRAGMA_DISABLE_DEPRECATION_WARNINGS
	~FNavLinkGenerationJumpConfig() = default;
	FNavLinkGenerationJumpConfig(const FNavLinkGenerationJumpConfig&) = default;
	FNavLinkGenerationJumpConfig(FNavLinkGenerationJumpConfig&&) = default;
	FNavLinkGenerationJumpConfig& operator=(const FNavLinkGenerationJumpConfig&) = default;
	FNavLinkGenerationJumpConfig& operator=(FNavLinkGenerationJumpConfig&&) = default;
	PRAGMA_ENABLE_DEPRECATION_WARNINGS

	/** Should this config be used to generate links. */
	UPROPERTY(EditAnywhere, Config, Category = Settings)
	bool bEnabled = true;

	/** A name for this config */
	UPROPERTY(EditAnywhere, Config, Category = Settings)
	FName Name;
	
	/** Horizontal length of the jump.
	 * How far from the starting point we will look for ground. */ 
	UPROPERTY(EditAnywhere, Config, Category = Settings, meta=(UIMin=0, ClampMin=0))
	float JumpLength = 150.f; 

	/** How far from the navmesh edge is the jump started. */
	UPROPERTY(EditAnywhere, Config, Category = Settings, meta=(UIMin=0, ClampMin=0))
	float JumpDistanceFromEdge = 10.f; 

	/** How far below the starting height we want to look for landing ground.
	 * A negative value can be used to generate a trajectory landing above the starting height
	 * (if negative, make sure to use a JumpHeight value big enough).
	 */
	UPROPERTY(EditAnywhere, Config, Category = Settings)
	float JumpMaxDepth = 150.f;

	/** Peak height relative to the height of the starting point. */
	UPROPERTY(EditAnywhere, Config, Category = Settings, meta=(UIMin=0, ClampMin=0))
	float JumpHeight = 50.f;

	/** Tolerance at both ends of the jump to find ground. */
	UPROPERTY(EditAnywhere, Config, Category = Settings, meta=(UIMin=0, ClampMin=0))
	float JumpEndsHeightTolerance = 80.f;

	/** Value multiplied by CellSize to find the distance between sampling trajectories. Default is 1.
     *  Larger values improve generation speed but might introduce sampling errors.  */
	UPROPERTY(EditAnywhere, Config, Category = Settings, meta=(UIMin=1, ClampMin=1))
	float SamplingSeparationFactor = 1.f;
	
	/** When filtering similar links, it's the distance used to compare between segment endpoints to match similar links.
	 * Use greater distance for more filtering (0 to deactivate filtering). */
	UPROPERTY(EditAnywhere, Config, Category = Settings, meta=(UIMin=0, ClampMin=0))
	float FilterDistanceThreshold = 80.f;

	/** Flags used to indicate how links will be added. */
	UPROPERTY(EditAnywhere, Config, Category = Settings, meta = (Bitmask, BitmaskEnum = "/Script/NavigationSystem.ENavLinkBuilderFlags"))
	uint16 LinkBuilderFlags = (uint16)ENavLinkBuilderFlags::CreateCenterPointLink;

#if WITH_EDITORONLY_DATA
	/** Area class for links generated by this configuration. */
	UE_DEPRECATED(5.6, "AreaClass is deprecated")
	UPROPERTY(Config, meta = (DeprecatedProperty, DeprecationMessage = "Use DownDirectionAreaClass and UpDirectionAreaClass instead."))
	TSubclassOf<UNavAreaBase> AreaClass_DEPRECATED;
#endif //WITH_EDITORONLY_DATA

	/**
	 * Area class for downward traversal of links generated by this configuration.
	 * @note If the value matches UpDirectionAreaClass, a single bidirectional link will be used to represent links generated by this configuration.
	 * If the value is null, no link will be generated in this direction
	 */
	UPROPERTY(EditAnywhere, Config, Category = Settings)
	TSubclassOf<UNavAreaBase> DownDirectionAreaClass;

	/**
	 * Area class for upward traversal of links generated by this configuration.
	 * @note If the value matches DownDirectionAreaClass, a single bidirectional link will be used to represent links generated by this configuration.
	 * If the value is null, no link will be generated in this direction
	 */
	UPROPERTY(EditAnywhere, Config, Category = Settings)
	TSubclassOf<UNavAreaBase> UpDirectionAreaClass;

	/** Class used to handle links made with this configuration.
	 * Using this allows to implement custom behaviors when using navlinks, for example during the pathfollow.
	 * Note that having a proxy is not required for successful navlink pathfinding,
	 * but it does allow for custom behavior at the start and the end of a given navlink.
	 * This implies that using LinkProxyClass is optional, and it can remain empty (the default value).
	 * @see INavLinkCustomInterface 
	 * @see UGeneratedNavLinksProxy
	 */
	UPROPERTY(EditAnywhere, Category= Settings)
	TSubclassOf<UBaseGeneratedNavLinksProxy> LinkProxyClass;

	/** Identifier used identify the current proxy handler. All links generated through this config will use the same handler. */
	UPROPERTY()
	FNavLinkId LinkProxyId;

	/** Current proxy. The proxy instance is build from the LinkProxyClass (provided it's not null).
	 * A proxy will be created if a @see LinkProxyClass is used.
	 */
	UPROPERTY(Transient)
	TObjectPtr<UBaseGeneratedNavLinksProxy> LinkProxy = nullptr;

	/** Is the link proxy registered to the navigation system CustomNavLinksMap.
	 * Registration occurs on PostRegisterAllComponents or on PostLoadPreRebuild if a new proxy was created. */
	UPROPERTY(Transient)
	bool bLinkProxyRegistered = false;

	/** Implemented for deprecated property cleanup purposes. */
	bool Serialize(FArchive& Ar);

#if WITH_RECAST	
	/** Copy configuration to dtNavLinkBuilderJumpConfig. */
	void CopyToDetourConfig(dtNavLinkBuilderJumpConfig& OutDetourConfig) const;
#endif //WITH_RECAST
};

template<> struct TStructOpsTypeTraits<FNavLinkGenerationJumpConfig> : public TStructOpsTypeTraitsBase2<FNavLinkGenerationJumpConfig>
{
	enum
	{
		WithSerializer = true
	};
};


PRAGMA_DISABLE_DEPRECATION_WARNINGS
struct dtNavLinkBuilderJumpDownConfig;

/** Experimental configuration to generate vertical links. */
USTRUCT()
struct UE_DEPRECATED(5.7, "Use FNavLinkGenerationJumpConfig instead.") FNavLinkGenerationJumpDownConfig
{
	GENERATED_BODY()

	FNavLinkGenerationJumpDownConfig();

	// Note: We need to explicitly disable warnings on these constructors/operators for clang to be happy with deprecated variables
	~FNavLinkGenerationJumpDownConfig() = default;
	FNavLinkGenerationJumpDownConfig(const FNavLinkGenerationJumpDownConfig&) = default;
	FNavLinkGenerationJumpDownConfig(FNavLinkGenerationJumpDownConfig&&) = default;
	FNavLinkGenerationJumpDownConfig& operator=(const FNavLinkGenerationJumpDownConfig&) = default;
	FNavLinkGenerationJumpDownConfig& operator=(FNavLinkGenerationJumpDownConfig&&) = default;

	/** Should this config be used to generate links. */
	UPROPERTY(Config)		// @todo Hidden for now. Since there is currently only one config, it has no real usage.
	bool bEnabled = true;
	
	/** Horizontal length of the jump.
	 * How far from the starting point we will look for ground. */ 
	UPROPERTY(EditAnywhere, Config, Category = Settings, meta=(UIMin=0, ClampMin=0))
	float JumpLength = 150.f; 

	/** How far from the navmesh edge is the jump started. */
	UPROPERTY(EditAnywhere, Config, Category = Settings, meta=(UIMin=0, ClampMin=0))
	float JumpDistanceFromEdge = 10.f; 

	/** How far below the starting height we want to look for landing ground. */
	UPROPERTY(EditAnywhere, Config, Category = Settings, meta=(UIMin=0, ClampMin=0))
	float JumpMaxDepth = 150.f;

	/** Peak height relative to the height of the starting point. */
	UPROPERTY(EditAnywhere, Config, Category = Settings, meta=(UIMin=0, ClampMin=0))
	float JumpHeight = 50.f;

	/** Tolerance at both ends of the jump to find ground. */
	UPROPERTY(EditAnywhere, Config, Category = Settings, meta=(UIMin=0, ClampMin=0))
	float JumpEndsHeightTolerance = 80.f;

	/** Value multiplied by CellSize to find the distance between sampling trajectories. Default is 1.
     *  Larger values improve generation speed but might introduce sampling errors.  */
	UPROPERTY(EditAnywhere, Config, Category = Settings, meta=(UIMin=1, ClampMin=1))
	float SamplingSeparationFactor = 1.f;
	
	/** When filtering similar links, it's the distance used to compare between segment endpoints to match similar links.
	 * Use greater distance for more filtering (0 to deactivate filtering). */
	UPROPERTY(EditAnywhere, Config, Category = Settings, meta=(UIMin=0, ClampMin=0))
	float FilterDistanceThreshold = 80.f;

	/** Flags used to indicate how links will be added. */
	UPROPERTY(EditAnywhere, Config, Category = Settings, meta = (Bitmask, BitmaskEnum = "/Script/NavigationSystem.ENavLinkBuilderFlags"))
	uint16 LinkBuilderFlags = (uint16)ENavLinkBuilderFlags::CreateCenterPointLink;

#if WITH_EDITORONLY_DATA
	/** Area class for links generated by this configuration. */
	UE_DEPRECATED(5.6, "AreaClass is deprecated")
	UPROPERTY(Config, meta = (DeprecatedProperty, DeprecationMessage = "Use DownDirectionAreaClass and UpDirectionAreaClass instead."))
	TSubclassOf<UNavAreaBase> AreaClass_DEPRECATED;
#endif //WITH_EDITORONLY_DATA

	/**
	 * Area class for downward traversal of links generated by this configuration.
	 * @note If the value matches UpDirectionAreaClass, a single bidirectional link will be used to represent links generated by this configuration.
	 * If the value is null, no link will be generated in this direction
	 */
	UPROPERTY(EditAnywhere, Config, Category = Settings)
	TSubclassOf<UNavAreaBase> DownDirectionAreaClass;

	/**
	 * Area class for upward traversal of links generated by this configuration.
	 * @note If the value matches DownDirectionAreaClass, a single bidirectional link will be used to represent links generated by this configuration.
	 * If the value is null, no link will be generated in this direction
	 */
	UPROPERTY(EditAnywhere, Config, Category = Settings)
	TSubclassOf<UNavAreaBase> UpDirectionAreaClass;

	/** Class used to handle links made with this configuration.
	 * Using this allows to implement custom behaviors when using navlinks, for example during the pathfollow.
	 * Note that having a proxy is not required for successful navlink pathfinding,
	 * but it does allow for custom behavior at the start and the end of a given navlink.
	 * This implies that using LinkProxyClass is optional, and it can remain empty (the default value).
	 * @see INavLinkCustomInterface 
	 * @see UGeneratedNavLinksProxy
	 */
	UPROPERTY(EditAnywhere, Category= Settings)
	TSubclassOf<UBaseGeneratedNavLinksProxy> LinkProxyClass;

	/** Identifier used identify the current proxy handler. All links generated through this config will use the same handler. */
	UPROPERTY()
	FNavLinkId LinkProxyId;

	/** Current proxy. The proxy instance is build from the LinkProxyClass (provided it's not null).
	 * A proxy will be created if a @see LinkProxyClass is used.
	 */
	UPROPERTY(Transient)
	TObjectPtr<UBaseGeneratedNavLinksProxy> LinkProxy = nullptr;

	/** Is the link proxy registered to the navigation system CustomNavLinksMap.
	 * Registration occurs on PostRegisterAllComponents or on PostLoadPreRebuild if a new proxy was created. */
	UPROPERTY(Transient)
	bool bLinkProxyRegistered = false;

	/** Implemented for deprecated property cleanup purposes. */
	bool Serialize(FArchive& Ar);

#if WITH_RECAST	
	/** Copy configuration to dtNavLinkBuilderJumpDownConfig. */
	void CopyToDetourConfig(dtNavLinkBuilderJumpDownConfig& OutDetourConfig) const;
#endif //WITH_RECAST
};

template<> struct TStructOpsTypeTraits<FNavLinkGenerationJumpDownConfig> : public TStructOpsTypeTraitsBase2<FNavLinkGenerationJumpDownConfig>
{
	enum
	{
		WithSerializer = true
	};
};
PRAGMA_ENABLE_DEPRECATION_WARNINGS